spring:
  application:
    name: springBook
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/springbook
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    ddl-auto: update
  show-sql: true

logging:
  level:
    root: error
